application: webcrontab
version: v1
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /run
  login: admin
  secure: always
  script: main.py

- url: /.*
  login: admin
  secure: always
  script: main.py

